<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Annisa Eka Wati">
<meta name="dcterms.date" content="2023-01-20">

<title>Analisis Pengaruh Jumlah Penduduk Terhadap Tingkat Kemiskinan di Kota Surakarta Periode 2017-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Jumlah Penduduk Terhadap Tingkat Kemiskinan di Kota Surakarta Periode 2017-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Annisa Eka Wati </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Kemiskinan merupakan salah satu permasalahan bagi negara-negara di dunia terutama pada negara berkembang. Bagi Indonesia yang merupakan salah satu negara berkembang yang ada di ASEAN, masalah kemiskinan bukanlah suatu hal yang baru. Hampir semua periode pemerintahan yang ada di Indonesia menempatkan masalah kemiskinan menjadi isu pembangunan. kemiskinan di Indonesia bersifat multidimensial. Menurut para ahli ekonomi (Arsyad, 2010) kemiskinan yang bersifat multidimensial dapat dilihat dari berbagai aspek diantaranya aspek primer dan aspek sekunder. Aspek primer berupa miskin aset, organisasi sosial politik, dan pengetahuan serta keterampilan yang rendah. Sedangkan aspek sekunder berupa miskin akan jaringan sosial, sumber keuangan, dan informasi. Permasalahan kemiskinan berhubungan erat dengan pembangunan karena term ini adalah dua hal yang sukar dipisahkan serta saling mempengaruhi satu dengan lainnya. Kemiskinan ialah tanggung jawab bersama terutama bagi pemerintah sebagai penyangga proses perbaikan kehidupan masyarakat dalam sebuah pemerintahan, untuk segera mencari jalan keluar sebagai upaya pemberantasan kemiskinan. Jumlah penduduk yang besar dapat menggerakan pasar dari permintaan melalui multiplier effect karena adanya aggregat demand. Penduduk dalam pembangunan ekonomi suatu daerah adalah masalah mendasr karena pertumbuhan penduduk yang tidak terkendali maka dapat mengakibatkan kegagalan untuk mencapai tujuan pembangunan ekonomi, yaitu kesejahteraan masyarakat dan pengentasan kemiskinan.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Dalam penelitian terdapat pembatasan masalah yang dilakukan guna membatasi topik permasalahan agar tetap sesuai tujuan penulisan serta menghindari penyimpangan pokok bahasan. Sesuai uraian yang terdapat dalam latar belakang, maka penulis menetapkan rumusan penelitian ini, yaitu pengaruh jumlah penduduk terhadap tingkat kemiskinan di Kota Surakarta.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah jumlah penduduk mempengaruhi tingkat kemiskinan di kota Surakarta tahun 2017-2021?</li>
<li>Bagaimana pengaruh jumlah penduduk terhadap tingkat kemiskinan di kota Surakarta tahun 2017-2021?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Penelitian ini dibuat dengan tujuan untuk mengetahui pengaruh dari jumlah penduduk dan pengangguran terhadap tingkat kemiskinan di Kota Surakarta dalam periode 2017-2021. Dengan mengetahui dampak yang ditimbulkan, maka diharapkan dapat menjadi salah satu bahan pertimbangan dalam mengambil kebijakan untuk menguranngi angka kemiskinan. Penelitian ini juga dibuat dibuat untuk memenuhi Ujian Akhir Semester (UAS) mata kuliah Metodologi Penelitian.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan dalam penelitian ini sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'D:/Metopel Nisa/UAS'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.1 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Data 1.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Studi pustaka</p>
<p>A. Kemiskinan</p>
<p>Salah satu akar permasalahan kemiskinan yaitu pertumbuhan penduduk yang tinggi, di mana tingkat kelahiran penduduk masih sangat tinggi, sedangkan tingkat kematiannya juga masih tinggi namun relatif sudah jauh lebih rendah. Menurut Malthus, kenaikan jumlah penduduk yang terus menerus merupakan unsur yang perlu untuk adanya tambahan permintaan. Tetapi kenaikan jumlah penduduk saja tanpa diikuti dengan kemajuan faktor-faktor atau unsur-unsur perkembangan yang lain sudah tentu tidak akan menaikkan pendapatan dan tidak akan menaikkan permintaan. Dengan demikian tumbuhnya jumlah penduduk saja justru akan menurunkan tingkat upah dan berarti pula memperendah biaya produksi. Turunnya biaya produksi akan memperbesar keuntungan-keuntungan para kapitalis dan mendorong mereka untuk terus berproduksi. Tetapi keadaan ini hanya sementara saja sifatnya, sebab permintaan efektif (effective demand) akan semakin berkurang karena pendapatan buruh juga semakin berkurang (Widarukmi, 2015).</p>
<p>B. Tingkat Kemiskinan</p>
<p>Lembaga Badan Pusat Statistik dalam Statistic Indonesia (2020) menjelaskan bahwa “penduduk adalah semua orang yang berdomisili di wilayah geografis Republik Indonesia selama 6 bulan atau lebih dan atau mereka yang berdomisili kurang dari 6 bulan tetapi bertujuan untuk menetap”. Adapun, menurut Said (2001), yang dimaksud dengan penduduk adalah “jumlah orang yang bertempat tinggal di suatu wilayah pada waktu tertentu dan merupakan hasil dari proses-proses demografi yaitu fertilitas, mortalitas, dan migrasi.”</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> DATA</h3>
<p>Data Jumlah Penduduk di Kota Surakarta</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Jumlah Penduduk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>515,54</td>
</tr>
<tr class="even">
<td>2018</td>
<td>515,87</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>517,05</td>
</tr>
<tr class="even">
<td>2020</td>
<td>522,36</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>522,73</td>
</tr>
</tbody>
</table>
<p>Data Jumlah Kemiskinan di Kota Surakarta</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Tingkat Kemiskinan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>54.890</td>
</tr>
<tr class="even">
<td>2018</td>
<td>46.990</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>45.180</td>
</tr>
<tr class="even">
<td>2020</td>
<td>47.030</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>48.790</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Data 1.xlsx'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat,<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">y=</span>Y)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.5</span>, <span class="at">size=</span><span class="dv">1</span>, <span class="at">color=</span><span class="st">'red'</span>) <span class="sc">+</span> <span class="co"># setiap nambah command, selalu kasih tanda +</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Jumlah Penduduk Terhadap Kemiskinan di Indonesia"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Angka Jumlah Penduduk"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Angka kemiskinan "</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistika"</span>)<span class="co"># yang terakhir ga perlu +</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mpg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-mpg-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: City and highway mileage for 38 popular models of cars.Color by number of cylinders</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode analisis yang digunakan pada penelitian ini menggunakan sumber data sekunder dari Badang Pusat Statistik Kota Surakarta. Data pada analisis penelitian ini ditulis secara sistemastis dan berbentuk urutan data waktu atau time series periode 2017-2021. Penelitian ini menggunakan teknik analisis kusntitatif dan menggunakan penjabaran deskriptif. Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud untuk mencari hubungan antara jumlah penduduk dengan tingkat kemiskinan di Kota Surakarta tahun 2017-2021.</p>
<p>Y^= a+bX</p>
<p>Y= variabel response atau dependent</p>
<p>X= variabel predictor atau independent</p>
<p>a=konstantan</p>
<p>b= koefisien regresi ; besaran response yang ditimbulkan oleh predictor</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Dikarenakan pada penelitian ini saya menggunakan metode OLS, maka saya hanya menghubungkan pengaruh jumlah penduduk terhadap tingkat kemiskinan di Kota Surakarta tahun 2017-2021.</p>
<p><img src="Rplot01.png" class="img-fluid"></p>
<p>Berdasarkan data plot diatas dapat diketahui bahwa tingkat kemiskinan paling besar terjadi di tahun 2017 sejumlah 54.890 jiwa dan tingkat kemiskinan paling rendah pada tahun 2019 sejumlah 45.180 jiwa.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Berikut ini hasil regresinya yang telah dilakukan</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Data 1.xlsx'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
      1       2       3       4       5 
 4.8702 -2.5482 -3.9288 -0.1429  1.7496 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 237.2933   275.5154   0.861    0.452
X            -0.3640     0.5313  -0.685    0.543

Residual standard error: 4.03 on 3 degrees of freedom
Multiple R-squared:  0.1352,    Adjusted R-squared:  -0.153 
F-statistic: 0.4692 on 1 and 3 DF,  p-value: 0.5425</code></pre>
</div>
</div>
<p>Berdasarkan hasil regresi diatas, dapat kita terjemahkan secara sederhana yaitu: Y^ = 237.2933 + (-0.3640)X</p>
<p>Nilai konstanta memiliki nilai positif sebesar 237.2933 yang menunjukkan pengaruh positif antara variabel dependent dan independent</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Pertumbuhan penduduk berkaitan dengan kemiskinan dan kesejahteraan masyarakat. Pengetahuan tentang aspek-aspek dan komponen demografi seperti fertilitas, mortalitas, morbiditas, migrasi, ketenagakerjaan, perkawinan, dan aspek keluarga dan rumah tangga akan membantu para penentu kebijakan dan perencana program untuk dapat mengembangkan program pembangunan kependudukan dan peningkatan kesejahteraan masyarakat yang tepat sasaran. Berdasarkan hasil analisis regresi linear sederhana dapat disimpulkan bahwa variabel dari Jumlah Penduduk (X) memiliki pengaruh negatif terhadap variabel Jumlah Kemiskinan (Y) di Kota Surakarta.</p>
</section>
<section id="saran" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="saran"><span class="header-section-number">6</span> Saran</h2>
<p>Berdasarkan uraian penelitian diatas, terdapat beberapa saran yang dapat dilakukan, sebagai berikut: 1) Menggalakkan program KB atau Keluarga Berencana untuk membatasi jumlah anak dalam suatu keluarga secara umum dan masal, sehingga akan mengurangi jumlah angka kelahiran. 2) Menunda masa perkawinan agar dapat mengurangi jumlah angka kelahiran yang tinggi. 3) Pengentasan kemiskinan melalui kebijakan kependudukan, seperti: a. Penerapan kebijakan kependudukan bagi pengentasan kemiskinan adalah dengan pencanangan KB (Keluarga berencana) dengan cara penyediaan kontrasepsi gratis bagi keluarga miskin. Hal ini dapat secara signifikan menurunkan tingkat kelahiran di keluarga miskin sehingga program penanganan kemiskinan yang dilakukan setelahnya dapat berjalan lebih optimal dan terasa. b. Pemerintah dapat menghemat dana program penanganan kemiskinan dengan mengalokasikannya ke kampanye penggunaan alat kontrasepsi. Selain itu, pemerintah daerah akan menjadi lebih fokus terhadap kelompok rumah tangga miskin yang sudah bisa mengendalikan tingkat kelahiran mereka. Beban tanggungan mereka yang berupa anak akan menjadi lebih sedikit, sehingga program penanganan kemiskinan akan lebih terasa dan bermakna untuk pengembangan mereka.</p>
</section>
<section id="referensi" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="referensi"><span class="header-section-number">7</span> Referensi</h2>
<p>Badan Pusat Statistik. (2022). Jumlah Penduduk Menurut Kabupaten/Kota di Provinsi Jawa Tengah, 2017-2021. BPS Kota Surakarta.</p>
<p>Badan Pusat Statistik. (2022). Jumlah Penduduk Miskin, 2013-2021. BPS Kota Surakarta.</p>
<p>Mulyadi. (2008). Ekonomi Sumber Daya manusia Dalam Perspektif Pembangunan. Jakarta : Rajawali Pers.</p>
<p>Said, Rusli. (2001). Pengantar Ilmu Kependudukan. Jakarta : Lembaga Penelitian dan Pengembangan Ekonomi dan Sosial.</p>
<p>Sukirno, S. (2004). Makro Ekonomi Teori Pengantar. Jakarta: Raja Grafindo Persada.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>